name: secrets not leaked

on:
  push:
    branches:
      - '**'

jobs:
  check-env-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for .env file in commit
        run: |
          if git ls-files --error-unmatch .env > /dev/null 2>&1; then
            echo ".env file is present in the commit. This is not allowed."
            exit 1
          else
            echo "No .env file found in the commit. Proceeding..."
          fi
